title: Lommi
email: enzo.marcell@ufms.br
description: >-
  Bem-vindo a lommi.studio, onde vocês poderão ver artigos interessantes sobre
  os mais variados temas :)
baseurl: ''
url: lommi.studio
twitter_username: '@enzo_marcell'
github_username: alypain
permalink: pretty
gem:
  - jekyll-admin
theme: minima
plugins:
  - jekyll-feed
